// Code generated by gen-check; DO NOT EDIT.
package codegen

import (
	"errors"
	"fmt"
	"net/mail"
)

func (u *User) Validate() error {
	if u.Name == "" {
		return errors.New("Name: required")
	}
	if len(u.Name) < 2 {
		return errors.New("Name: min 2")
	}
	if u.Email == "" {
		return errors.New("Email: required")
	}
	if _, err := mail.ParseAddress(u.Email); err != nil {
		return fmt.Errorf("Email: %w", err)
	}
	return nil
}

func (s *Signup) Validate() error {
	if s.Username == "" {
		return errors.New("Username: required")
	}
	if len(s.Username) < 3 {
		return errors.New("Username: min 3")
	}
	if s.Email == "" {
		return errors.New("Email: required")
	}
	if _, err := mail.ParseAddress(s.Email); err != nil {
		return fmt.Errorf("Email: %w", err)
	}
	return nil
}
