// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: grpc/api/greeter.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Formality     int32                  `protobuf:"varint,2,opt,name=formality,proto3" json:"formality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_grpc_api_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GreetRequest) GetFormality() int32 {
	if x != nil {
		return x.Formality
	}
	return 0
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_grpc_api_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FarewellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellRequest) Reset() {
	*x = FarewellRequest{}
	mi := &file_grpc_api_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellRequest) ProtoMessage() {}

func (x *FarewellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellRequest.ProtoReflect.Descriptor instead.
func (*FarewellRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *FarewellRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FarewellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellResponse) Reset() {
	*x = FarewellResponse{}
	mi := &file_grpc_api_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellResponse) ProtoMessage() {}

func (x *FarewellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellResponse.ProtoReflect.Descriptor instead.
func (*FarewellResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *FarewellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_api_greeter_proto protoreflect.FileDescriptor

const file_grpc_api_greeter_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/api/greeter.proto\x12\tgreeterpb\"E\n" +
	"\fGreetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tformality\x18\x02 \x01(\x05R\tformality\")\n" +
	"\rGreetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x0fFarewellRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\",\n" +
	"\x10FarewellResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8a\x01\n" +
	"\aGreeter\x12:\n" +
	"\x05Greet\x12\x17.greeterpb.GreetRequest\x1a\x18.greeterpb.GreetResponse\x12C\n" +
	"\bFarewell\x12\x1a.greeterpb.FarewellRequest\x1a\x1b.greeterpb.FarewellResponseB1Z/github.com/rednafi/examples/wire-plumb/grpc/apib\x06proto3"

var (
	file_grpc_api_greeter_proto_rawDescOnce sync.Once
	file_grpc_api_greeter_proto_rawDescData []byte
)

func file_grpc_api_greeter_proto_rawDescGZIP() []byte {
	file_grpc_api_greeter_proto_rawDescOnce.Do(func() {
		file_grpc_api_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_api_greeter_proto_rawDesc), len(file_grpc_api_greeter_proto_rawDesc)))
	})
	return file_grpc_api_greeter_proto_rawDescData
}

var file_grpc_api_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_api_greeter_proto_goTypes = []any{
	(*GreetRequest)(nil),     // 0: greeterpb.GreetRequest
	(*GreetResponse)(nil),    // 1: greeterpb.GreetResponse
	(*FarewellRequest)(nil),  // 2: greeterpb.FarewellRequest
	(*FarewellResponse)(nil), // 3: greeterpb.FarewellResponse
}
var file_grpc_api_greeter_proto_depIdxs = []int32{
	0, // 0: greeterpb.Greeter.Greet:input_type -> greeterpb.GreetRequest
	2, // 1: greeterpb.Greeter.Farewell:input_type -> greeterpb.FarewellRequest
	1, // 2: greeterpb.Greeter.Greet:output_type -> greeterpb.GreetResponse
	3, // 3: greeterpb.Greeter.Farewell:output_type -> greeterpb.FarewellResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_api_greeter_proto_init() }
func file_grpc_api_greeter_proto_init() {
	if File_grpc_api_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_api_greeter_proto_rawDesc), len(file_grpc_api_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_api_greeter_proto_goTypes,
		DependencyIndexes: file_grpc_api_greeter_proto_depIdxs,
		MessageInfos:      file_grpc_api_greeter_proto_msgTypes,
	}.Build()
	File_grpc_api_greeter_proto = out.File
	file_grpc_api_greeter_proto_goTypes = nil
	file_grpc_api_greeter_proto_depIdxs = nil
}
